import java.nio.file.*;
import java.io.IOException;

public class GenerateEntities3 {
    public static void main(String[] args) throws IOException {
        String baseDir = "src/main/java/com/kawai/models/core/";
        Files.createDirectories(Paths.get(baseDir));

        write(baseDir + "TableReservation.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.time.LocalDate;\nimport java.time.LocalTime;\n@Entity\n@Table(name = \"Table_Reservations\")\n@Data\npublic class TableReservation {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"customer_id\") private Customer customer;\n    @ManyToOne @JoinColumn(name = \"table_id\") private RestaurantTable table;\n    @Column(name = \"reserve_date\") private LocalDate reserveDate;\n    @Column(name = \"reserve_time\") private LocalTime reserveTime;\n    @Enumerated(EnumType.STRING) private ReservationStatus status;\n    public enum ReservationStatus { PENDING, CONFIRMED, COMPLETED, CANCELLED }\n}");

        write(baseDir + "FoodOrder.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.math.BigDecimal;\n@Entity\n@Table(name = \"Food_Orders\")\n@Data\npublic class FoodOrder {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"room_booking_detail_id\") private RoomBookingDetail roomBookingDetail;\n    @ManyToOne @JoinColumn(name = \"table_id\") private RestaurantTable table;\n    @Enumerated(EnumType.STRING) @Column(name = \"order_type\") private OrderType orderType;\n    @Column(name = \"total_amount\") private BigDecimal totalAmount;\n    @Enumerated(EnumType.STRING) @Column(name = \"order_status\") private OrderStatus orderStatus;\n    public enum OrderType { ROOM_SERVICE, RESTAURANT }\n    public enum OrderStatus { PENDING, PROCESSING, COMPLETED, CANCELLED }\n}");

        write(baseDir + "FoodOrderDetail.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.math.BigDecimal;\n@Entity\n@Table(name = \"Food_Order_Details\")\n@Data\npublic class FoodOrderDetail {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"food_order_id\") private FoodOrder foodOrder;\n    @ManyToOne @JoinColumn(name = \"menu_item_id\") private MenuItem menuItem;\n    private Integer quantity;\n    @Column(name = \"price_at_order\") private BigDecimal priceAtOrder;\n    @Enumerated(EnumType.STRING) @Column(name = \"kot_status\") private KotStatus kotStatus;\n    public enum KotStatus { PENDING, PREPARING, READY, SERVED }\n}");

        write(baseDir + "HotelOperation.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.time.LocalDateTime;\n@Entity\n@Table(name = \"Hotel_Operations\")\n@Data\npublic class HotelOperation {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @Enumerated(EnumType.STRING) @Column(name = \"task_type\") private TaskType taskType;\n    @ManyToOne @JoinColumn(name = \"room_id\") private Room room;\n    @ManyToOne @JoinColumn(name = \"staff_id\") private Employee staff;\n    @ManyToOne @JoinColumn(name = \"supervisor_id\") private Employee supervisor;\n    @Enumerated(EnumType.STRING) @Column(name = \"task_status\") private TaskStatus taskStatus;\n    @Enumerated(EnumType.STRING) private Priority priority;\n    private String description;\n    @Column(name = \"created_at\") private LocalDateTime createdAt;\n    @Column(name = \"completed_at\") private LocalDateTime completedAt;\n    public enum TaskType { HOUSEKEEPING, MAINTENANCE, ROOM_SERVICE }\n    public enum TaskStatus { TODO, IN_PROGRESS, REVIEW, DONE }\n    public enum Priority { LOW, MEDIUM, HIGH, URGENT }\n}");

        write(baseDir + "FolioItem.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.math.BigDecimal;\nimport java.time.LocalDateTime;\n@Entity\n@Table(name = \"Folio_Items\")\n@Data\npublic class FolioItem {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"booking_id\") private Booking booking;\n    @Enumerated(EnumType.STRING) @Column(name = \"source_department\") private Department sourceDepartment;\n    private BigDecimal amount;\n    private String description;\n    @Column(name = \"created_at\") private LocalDateTime createdAt;\n    @Column(name = \"signature_img_url\") private String signatureImgUrl;\n    @Column(name = \"is_settled\") private Boolean isSettled;\n    public enum Department { ROOM, RESTAURANT, SPA, TOUR, MINIBAR, LAUNDRY }\n}");

        write(baseDir + "ConsolidatedInvoice.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.math.BigDecimal;\nimport java.time.LocalDateTime;\n@Entity\n@Table(name = \"Consolidated_Invoices\")\n@Data\npublic class ConsolidatedInvoice {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"booking_id\") private Booking booking;\n    @Column(name = \"total_amount\") private BigDecimal totalAmount;\n    @Column(name = \"tax_amount\") private BigDecimal taxAmount;\n    @Column(name = \"discount_amount\") private BigDecimal discountAmount;\n    @Column(name = \"final_amount\") private BigDecimal finalAmount;\n    @Enumerated(EnumType.STRING) @Column(name = \"invoice_status\") private InvoiceStatus invoiceStatus;\n    @Column(name = \"created_at\") private LocalDateTime createdAt;\n    public enum InvoiceStatus { DRAFT, ISSUED, PAID, CANCELLED }\n}");

        write(baseDir + "PaymentTransaction.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.math.BigDecimal;\nimport java.time.LocalDateTime;\n@Entity\n@Table(name = \"Payment_Transactions\")\n@Data\npublic class PaymentTransaction {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"invoice_id\") private ConsolidatedInvoice invoice;\n    @ManyToOne @JoinColumn(name = \"booking_id\") private Booking booking;\n    private BigDecimal amount;\n    @Enumerated(EnumType.STRING) @Column(name = \"transaction_type\") private TransactionType transactionType;\n    @Enumerated(EnumType.STRING) @Column(name = \"payment_method\") private PaymentMethod paymentMethod;\n    @Column(name = \"gateway_status\") private String gatewayStatus;\n    @Column(name = \"transaction_ref\", unique = true) private String transactionRef;\n    @Column(name = \"created_at\") private LocalDateTime createdAt;\n    public enum TransactionType { DEPOSIT, FINAL_PAYMENT, REFUND }\n    public enum PaymentMethod { CASH, CREDIT_CARD, BANK_TRANSFER, VNPAY, MOMO }\n}");

        write(baseDir + "Review.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.time.LocalDateTime;\n@Entity\n@Table(name = \"Reviews\")\n@Data\npublic class Review {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"customer_id\") private Customer customer;\n    @ManyToOne @JoinColumn(name = \"booking_id\") private Booking booking;\n    @Column(name = \"rating_score\") private Integer ratingScore;\n    @Column(name = \"review_text\") private String reviewText;\n    @Column(name = \"created_at\") private LocalDateTime createdAt;\n    @Enumerated(EnumType.STRING) @Column(name = \"moderation_status\") private ModerationStatus moderationStatus;\n    @ManyToOne @JoinColumn(name = \"moderated_by\") private Employee moderatedBy;\n    @Column(name = \"moderation_reason\") private String moderationReason;\n    public enum ModerationStatus { PENDING, APPROVED, REJECTED }\n}");

        write(baseDir + "DynamicPricing.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.math.BigDecimal;\nimport java.time.LocalDate;\n@Entity\n@Table(name = \"Dynamic_Pricing\")\n@Data\npublic class DynamicPricing {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"category_id\") private RoomCategory category;\n    @Column(name = \"start_date\") private LocalDate startDate;\n    @Column(name = \"end_date\") private LocalDate endDate;\n    @Column(name = \"price_modifier\") private BigDecimal priceModifier;\n    private String reason;\n}");

        write(baseDir + "Promotion.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.math.BigDecimal;\nimport java.time.LocalDateTime;\n@Entity\n@Table(name = \"Promotions\")\n@Data\npublic class Promotion {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @Column(name = \"promo_code\", unique = true) private String promoCode;\n    @Enumerated(EnumType.STRING) @Column(name = \"discount_type\") private DiscountType discountType;\n    @Column(name = \"discount_value\") private BigDecimal discountValue;\n    @Column(name = \"valid_from\") private LocalDateTime validFrom;\n    @Column(name = \"valid_to\") private LocalDateTime validTo;\n    @Column(name = \"max_uses\") private Integer maxUses;\n    @Column(name = \"current_uses\") private Integer currentUses;\n    public enum DiscountType { PERCENTAGE, FIXED_AMOUNT }\n}");

        write(baseDir + "AuditLog.java", "package com.kawai.models.core;\nimport jakarta.persistence.*;\nimport lombok.Data;\nimport java.time.LocalDateTime;\n@Entity\n@Table(name = \"Audit_Logs\")\n@Data\npublic class AuditLog {\n    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;\n    @ManyToOne @JoinColumn(name = \"account_id\") private Account account;\n    @Enumerated(EnumType.STRING) private Action action;\n    @Column(name = \"table_name\") private String tableName;\n    @Column(name = \"record_id\") private Long recordId;\n    @Column(name = \"old_values\", columnDefinition = \"JSON\") private String oldValues;\n    @Column(name = \"new_values\", columnDefinition = \"JSON\") private String newValues;\n    @Column(name = \"ip_address\") private String ipAddress;\n    @Column(name = \"created_at\") private LocalDateTime createdAt;\n    public enum Action { INSERT, UPDATE, DELETE, LOGIN, LOGOUT }\n}");

        System.out.println("Entities 3 generated successfully!");
    }

    private static void write(String path, String content) throws IOException {
        Files.writeString(Paths.get(path), content);
    }
}
