spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 538898392088-lv7in7thft76gbj9dki3u6ko1itmnrda.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/kawai_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

vnpay:
  tmn-code: 77G0NGGT
  hash-secret: 4JVVJ2NUMIMEWODNGA3CR8DV52L5PKII
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/v1/payments/vnpay-return
  api-version: 2.1.0