spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 538898392088-lv7in7thft76gbj9dki3u6ko1itmnrda.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:h2:mem:kawai_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: UTF-8
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false

server:
  port: 8080
