spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 538898392088-lv7in7thft76gbj9dki3u6ko1itmnrda.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:mysql://localhost:3306/kawai_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Luu14102005@
  sql:
    init:
      mode: always
      encoding: UTF-8
      continue-on-error: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

server:
  port: 8080
